# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-09 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'permissions': (('change_balance', 'Peut modifier son ardoise'),), 'verbose_name': 'Utilisateur'},
        ),
    ]
